language: c
os:
    - osx
    - linux
install: 
    - mkdir -p build
    - cd build
    - wget -q http://embedthis.com/software/makeme-0.10.0-src.tgz -O makeme.tgz
    - tar xvfz makeme.tgz
    - cd makeme-*
    - make boot 
    - sudo make install
    - cd ../..
script:
    - ./configure
    - me -s
    - me test
